services:
  - type: web
    name: recipe-saver-backend
    runtime: node
    rootDir: recipe-saver/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SPOONACULAR_API_KEY
        sync: false
